새로운 branch 열어서 Pull Request 생성
justakim12/simple_projects_withJavaScript pull request #2
Opened 2020-11-02 14:16 UTC by justakim12

2020-11-02 15:40 UTC, HyunSangHan requested changes
branch 잘 따서 진행해주셨네요.

보통 develop브랜치가 있으면 feature브랜치가 있습니다.
부모자식관계로 보면 main - develop - feature가 됩니다.
제가 develop브랜치를 만들라고 권해드렸던 이유는 develop브랜치 하나로 쭉 작업을 하실 걸로 예상했어서인데요.
1. 만일 여러 작업을 여러 PR에 나눠서 올리실 거라면 앞으로 예컨대 `feature/resize-center-align` 이런식으로 작업단위별로 이름을 따로 지어서 매번 PR을 올리시면 될 것 같네요.
2. 만일 여러 작업을 한 PR에 모아서 올리실 거라면 지금처럼 `develop/calculator` 브랜치 하나만 두고, 앞으로 계속 여기에 커밋하시면 됩니다.

그리고 커밋명을 좀더 유의미하게 써주시면 좋을 것 같습니다. 이 내용을 참고하세요. https://blog.ull.im/engineering/2019/03/10/logs-on-git.html

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/index.html
> +        <div class = 'cal-group'>
1. 보통 띄어쓰기를 안넣는 게 일반적인 것 같습니다.
2. 그리고 다른 곳에선 쌍따옴표를 썼었으니 쌍따옴표로 통일하는 게 낫겠습니다.
```suggestion
        <div class="cal-group">
```

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/index.html
> +            <input type=button value="=" Onclick="calc.display.value=eval(calc.display.value)" style="background-color:pink;">
1. `onClick` 부분은 JS의 영역이라고 볼 수 있는데, 보통 따로 `<script> ... </script>` 형태로 빼서 JS부분(정확히는, eventListner 등)을 작성하고 HTML부분에 심는 게 일반적입니다. 따라서 일단 `onClick` 부분은 모두 지워두고 스타일에만 집중하기로 합시다.
2. `eval`은 안쓰는 게 좋습니다. _eval is evil_ 이라는 말이 있습니다. https://velog.io/@modolee/javascript-eval-is-evil

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/index.html
> +            <input name="display" style="width:675px; height:100px;
들여쓰기는 코딩습관에서 매우 중요합니다.
위에 `<form>` 태그가 있으니 그 자식 엘리먼트인 `<input>`들은 더 들여쓰기를 해서 구분지어야 합니다.

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/mystyle.css
>   input {
가급적이면 tagName 기준으로 스타일링은 지정하지 않는 게 좋습니다.

참고로, 기본적으로는 3가지 방법이 있습니다.
1. `tag(tagName)`: 위 input처럼 그냥 태그네임을 바로 씁니다.
2. `id`: `#`을 앞에 붙입니다.(아래 `#myform`처럼)
3. `class(className)`: `.`을 앞에 붙입니다. 아래는 예시입니다.
    ```css
    .some-class-name {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    ```

이중에서 가장 일반적인 방법은 3번입니다. class는 다수에 적용되어도 괜찮고, id는 unique해야한다(그 id는 단 1개의 엘리먼트만 가질 수 있다)는 점이 차이점입니다.

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/mystyle.css
> +    text-align: center;
text-align이 정렬할 때 제일 쉽긴 하지만 이걸로는 좀 한계가 있습니다.

`display` 라는 녀석과 `position`, `float`에 대해서도 공부해보세요.(css의 기본이자 필수적인 개념입니다.)
어떤 때 쓰는지 차이점을 아는 게 매우 중요합니다.

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/mystyle.css
> +
불필요한 공백줄은 제거하면 좋습니다.
보통 맨 마지막 공백라인은 1줄만 둡니다.

2020-11-02 15:40 UTC, HyunSangHan commented on simple_calculator/index.html
> +            <input type=button value="0" Onclick="calc.display.value+='0'">
`<input type=button>`도 있지만 `<button>`도 버튼을 만드는 방법입니다.
그런데 꼭 버튼을 만들지 않아도 `<div>`로도 버튼스럽게 만들 수가 있습니다. 커스터마이징할 때에는 <div>를 많이 쓰게 되니 초반에는 <div>로 많이 연습해보세요.
(물론 웹접근성 차원에서 용도에 맞는 tag를 쓰는 게 궁극적으로는 더 중요하긴 합니다. 하지만 HTML/CSS 입문차원에서 div를 추천한 것입니다.)

2020-11-02 15:42 UTC, HyunSangHan commented
css 관련해서 `hover`라는 게 있는데요.
계산기 보시면 보통 마우스오버했을 때 그 칸의 색깔이 변합니다. 그걸 구현할 때 `hover`라는 개념이 들어갑니다.
참고해서 더 그럴듯하게 만들어보세요!

2020-11-02 16:08 UTC, HyunSangHan commented
### 스타일링
iPhone X(너비: 375px) 기준으로 아래와 같이 깨지고 있습니다.
![image](https://user-images.githubusercontent.com/44132406/97890484-ed514100-1d70-11eb-8b41-afa73f988f76.png)

이 계산기 과제에 대해서는 경일님이 개발자 포지션이고 제가 기획자인 셈인데요. 기획자의 요구사항은 아래와 같은 형태입니다.
http://calculator.dothome.co.kr/ 너비를 줄였다 늘렸다 해가며 예시를 참고해보세요~

2020-11-03 14:09 UTC, justakim12 commented on simple_calculator/mystyle.css
>   input {
HTML에 정의하는 tag이름이랑 CSS가 달라도 알맞게 적용이 되는건가요? 저는 이름이 동일해야 적용이 되는걸로 알고 있어서 여쭤봅니다!

2020-11-03 14:10 UTC, justakim12 commented on simple_calculator/index.html
> +            <input type=button value="0" Onclick="calc.display.value+='0'">
내용이 생략이 된것 같네요....커스터마이징할때 뭐를 많이 쓰게되는거죠?ㅜ

2020-11-03 14:13 UTC, justakim12 commented on simple_calculator/index.html
> +        <div class = 'cal-group'>
새로운 commit으로 반영 완료

2020-11-03 14:13 UTC, justakim12 commented on simple_calculator/index.html
> +            <input name="display" style="width:675px; height:100px;
새로운 commit으로 반영 완료

2020-11-03 14:14 UTC, justakim12 commented on simple_calculator/mystyle.css
> +
새로운 commit으로 반영 완료

2020-11-03 14:39 UTC, HyunSangHan commented on simple_calculator/index.html
> +            <input type=button value="0" Onclick="calc.display.value+='0'">
엇..ㅎㅎ HTML태그가 적용되어버렸네요. \``로 감쌈으로써 보이게끔 수정했습니다.
혹시 이런 경우가 또 보이면 그 코멘트의 Edit버튼을 눌러보면 원 내용이 보입니다.

2020-11-03 14:46 UTC, HyunSangHan commented on simple_calculator/mystyle.css
>   input {
```html
<button id="someId" class="some-class-name">
```

위와 같은 HTML Element가 있다고 가정할 때, 이 엘리멘트의 색깔을 검정색으로 만드는 방법은 CSS 작성법은 아래 세가지입니다.

### 1. tag
```css
button {
    background-color: #000;
}
```

### 2. id
```css
#someId {
    background-color: #000;
}
```

### 3. class
```css
.some-class-name {
    background-color: #000;
}
```

따라서 2와 3의 경우 tag이름이랑 상관없는데도 스타일링을 지정할 수 있게 됩니다.
1, 2, 3의 각 차이점은 위 코멘트 https://github.com/justakim12/simple_projects_withJavaScript/pull/2#discussion_r516051099 에 남긴 것과 같습니다.

2020-11-03 14:49 UTC, HyunSangHan commented on simple_calculator/mystyle.css
> +.cal-group-class {
`simple_calculator/index.html` 파일의 15번째줄에

```html
<div class="cal-group">
```

와 같이, `cal-group`이라는 이름의 className을 쓰고 있기 때문에, 여기 css에서도 `.cal-group`이라는 이름을 써야 매칭이 됩니다.

```suggestion
.cal-group {
```

2020-11-03 15:01 UTC, justakim12 commented on simple_calculator/index.html
> +            <input type=button value="=" Onclick="calc.display.value=eval(calc.display.value)" style="background-color:pink;">
onClick 제외하고 스타일에 집중 완료

2020-11-03 15:05 UTC, justakim12 commented
@HyunSangHan 
- 우선 Style에 집중할 수 있게 JS 부분들은 모두 제거하고, hover는 추가했습니다. 또한 형태들도 조언주신대로 모두 수정했습니다. 
- Resizable하게 하는게 쉽지 않네요...width/height를 %로 바꾸면서 수정 중인데요, 이것저것 테스트 해보겠습니다. 
- 해당 branch에 우선 계속 commit를 여러개 올리고 한번에 merge하는 것을 생각하긴 했는데요, 효율적인 절차를 잘 몰라서...의견주면 그거에 따라 진행해보겠습니다!

2020-11-03 15:26 UTC, HyunSangHan commented
@justakim12 
> 우선 Style에 집중할 수 있게 JS 부분들은 모두 제거하고, hover는 추가했습니다. 또한 형태들도 조언주신대로 모두 수정했습니다.

=> 넵 요거 https://github.com/justakim12/simple_projects_withJavaScript/pull/2#discussion_r516723369 는 추가로 수정 필요해보입니다.

> Resizable하게 하는게 쉽지 않네요...width/height를 %로 바꾸면서 수정 중인데요, 이것저것 테스트 해보겠습니다.

=> 이건 한번 구글밋으로 알려드리는 게 편할 거에요. 일정은 따로 연락해서 조율해봅시다.

> 해당 branch에 우선 계속 commit를 여러개 올리고 한번에 merge하는 것을 생각하긴 했는데요, 효율적인 절차를 잘 몰라서...의견주면 그거에 따라 진행해보겠습니다!

=> 대략 2가지 방법이 있습니다.
1. main브랜치에서 develop/calculator 브랜치를 땄던 것처럼, develop/calculator에서 feature/blahblah 브랜치를 따기. 그러고 feature/blahblah 브랜치 작업한 걸 develop/calculator로 PR보내기. 그 PR을 Merge시키면 그때서야 develop/calculator에 커밋이 반영됨. 이런식으로 (1) feature브랜치 따고 (2) develop브랜치에 머지시키고.. 하는 걸 반복해서 develop브랜치에 커밋을 쌓고, (3) develop브랜치를 main브랜치에 반영하기
2. 지금 하고있는 것처럼, develop/calculator브랜치에다가 계속 로컬에서 직접 커밋을 남겨서 push 하기.

1처럼 하면 가장 현업스럽고 좋은데, 그건 git을 좀더 학습한 후 다음 프로젝트에서 해보기로 하고, 일단 2로 진행하면 될 것 같습니다.

그러려면 이 PR의 title이 `새로운 branch 열어서 Pull Request 생성. Resize를 Center에 Align하도록 수정`처럼 specific해지면 안되고, `calculator UI 개선` 이런식으로 general해져야 어울릴 것 같습니다. 제목수정버튼은 제목 우측에 있으니 참고하세요.

2020-11-03 23:18 UTC, justakim12 commented
@HyunSangHan 
- 제목 수정 완료
- css class name 수정하는 commit 반영 완료
- 현재 2안처럼 develop branch에 계속 commit하고 한번에 merge 진행하겠습니다
- resizable은 조금 공부한 뒤에 반영할게요

2020-11-04 14:12 UTC, merged

2020-11-04 15:50 UTC, HyunSangHan commented
@justakim12 
승현님 PR 보시고 의견있으시면 코드리뷰도 달아주세요.
https://github.com/bewisesh91/HTML-CSS_practice/pull/1

승현님작업을 경일님 로컬에서 테스트해보는 방법은,
1. 승현님 레포지토리를 클론 받는다.
2. 클론받고나면 그 레포지토리 이름으로 디렉토리가 만들어지는데, 그 디렉토리 안으로 들어간다 `cd 디렉토리명`
3. 참고로 git은 처음엔 main브랜치로 설정되어 있을건데.. `git fetch`를 해서 모든 브랜치를 리모트로부터 모두 내려받는다.
4. `git checkout branch_1`해서 승현님이 작업한 브랜치로 이동한다.
5. `open index.html`한다.